application: aranalibtest
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /app/media/(.*\.(gif|png|jpg|ico|css))
  static_files: app/media/\1
  upload: app/media/(.*\.(gif|png|jpg|ico|css))

- url: /media
  static_dir: _generated_media

- url: /.*
  script: common/appenginepatch/main.py
